---
title: "Homework 2"
author: "Julia Thompson"
date: "10/1/2019"
output: github_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(readxl)
```

## Problem 1

```{r}
trash_data = read_excel(
  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "Mr. Trash Wheel",
  range = "A2:N408") %>%
  janitor::clean_names() %>%
  drop_na(dumpster) %>%
  mutate(sports_balls = as.integer(sports_balls))
```

Read and clean precipitation data for 2017 and 2018. For each, omit rows without precipitation data and add a variable year. 

```{r}
precip_2017 = read_excel(
  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2017 Precipitation",
  skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2017)

precip_2018 = read_excel(
  path = "./data/Trash-Wheel-Collection-Totals-8-6-19.xlsx",
  sheet = "2018 Precipitation",
  skip = 1) %>% 
  janitor::clean_names() %>% 
  drop_na(month) %>% 
  mutate(year = 2018)
```

Next, combine precipitation datasets and convert month to a character variable (the variable month.name is built into R and should be useful).

```{r}

```

